### ISSUE TITLE
New command to fetch data from an unmounted volume

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/kubectl-ran#12]
## Use Case
Sometimes a pod is in CrashLoopBackOff due to data in a persistent volume. Getting data out of that volume requires the right timing. It'd be useful to have a way to grab the contents of the volume reliably.

## Describe the Solution You Would Like
```
kubectl-grab <pvc> [--output ./local/path]
```

## Describe Alternatives You've Considered
kubectl debug could help with this problem, but is not widely available yet.

## Additional Context
Can be approximated with a `mount.yaml`
```yaml
spec:
  volumes:
    - name: worker
      persistentVolumeClaim:
        claimName: <pvc>
  containers:
    - name: worker
      volumeMounts:
        - mountPath: /data
          name: worker
```
and
```
kubectl ran busybox --pod-file mount.yaml --volume ./local/path:/data -- true
```
